spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workbook7th
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  spring:
    security:
      oauth2:
        client:
          registration:
            kakao:
              client-authentication-method: client_secret_post
              client-id: cc8180a5cf015577f0a1d6f614060342
              client-secret: kY1OjHwOUT4nbLotoxXCeKgQofYS7hTC
              redirect-uri: http://localhost:8080/login/oauth2/code/kakao
              authorization-grant-type: authorization_code
              scope: profile_nickname
              client-name: Kakao
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id